### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by reederz** [gatesense/node-red-contrib-coap#4]
Sometimes, I get this error from node-coap:
24 Dec 18:03:03 - [red] Uncaught Exception:
24 Dec 18:03:03 - Error: No reply in 247s
    at null._onTimeout (/vagrant/node-red-contrib-coap/node_modules/coap/lib/retry_send.js:61:18)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by milaw** [comment]
Hi,

I want to make a out node for coap ( coap-in -> coap out) like http.
Can you give some advice to make it ? Do I need to make change to coap-in?

I really noob in node.js/node-red, thus your help will be very welcome!! ;)

Thanks
Michael.

**Comment by reederz** [comment]
We don't have a dedicated "coap out" node. You can simulate one with a function node with this code in:
```js
msg.res.end("response text");
return res;
```

Please see the *./examples* directory of this repo

**Comment by milaw** [comment]
Hi,

Thanks for your answer.
I saw the example, but I want to made one.
I will work on it.
I'm working in the meantime on the client to add others coap options. I
will care the test soon.

Thanks
M.

**Comment by MadhuriLShastry** [comment]
Is there an alternative solution to that issue? instead of using forever...
I am using node-red-contrib-freeboard and that stops working after 247s even though node red is running when i use forever.

**Comment by reederz** [comment]
@MadhuriLShastry I think it's some sort of internal timeout in node-coap- you're welcome to make a PR for this. If you're going to do it- you could also talk to @mcollina . Otherwise, if you're not up for it, I'll try to fix it some time soon.

**Comment by MadhuriLShastry** [comment]
I am not very familiar to node.js or node red...can you please guide me on how to do it?
Thank you :)

**Comment by reederz** [comment]
OK, in that case I'll do it myself this week. If you want to learn either node.js or node-red you're best off starting with some basics instead of jumping in like this. Good luck

**Comment by mcollina** [comment]
Thanks @reederz :D. If it's a bug on node-coap I'll add you as committer there, and we can make it work :D.

**Comment by reederz** [comment]
No problem. I'm not certain whether it's node-coap's bug - gonna check 
it later this week :)

**Comment by reederz** [comment]
@mcollina no bugs in node-coap- it was my fault because I didn't handle errors on client and server side. The particular error in this case is one thrown by node-coap when EXCHANGE_LIFETIME (247 seconds) is reached. To be more precise, coap server doesn't send the necessary acks to the client run inside node-red. Since we live in an imperfect world where you can't expect servers to be responsive all the time, this error has to be handled gracefully instead of letting it crash the whole node-red runtime :)

@milaw @MadhuriLShastry the fix for this bug is in v0.1.0 .

**Comment by MadhuriLShastry** [comment]
Thank you!! :)
